### ISSUE TITLE
property numeric values are meaningless

### ISSUE THREAD

**Issue by whot** [IvanFon/xinput-gui#2]
Based on the screenshots in the readme, you show the property ID. That's not necessary, that value is completely meaningless and is only used for optimization on lookup (it's an Atom which works as the key because hello, 1980s). Think of it as a database index.

So I recommend dropping that column, it doesn't add any value for the user.

**Comment by IvanFon** [comment]
Fixed in commit da55d0cca85e0b2280532c675253b05e489017fc.

The property ID column is now hidden by default. I've still kept in a setting to enable the column if needed (mostly because I use them to quickly reference propeties when manually typing in `xinput` commands).

Thanks!

**Comment by whot** [comment]
fwiw, I'm pretty sure at least zsh has xinput autocompletion. unless that's still some local hack that's sitting around in my .zshrc
