### ISSUE TITLE
"SyntaxError: invalid syntax" when executing /usr/bin/xinput-gui post install

### ISSUE THREAD

**Issue by sangeet** [IvanFon/xinput-gui#3]
I am getting the following error upon first run of the app. Not sure what's up since I don't have enough knowledge of python to make any sense of the error message that I got upon the first run of the app.

The installation was done with the standard procedure mentioned in the website. i.e untar followed by the python command.

**Error :** 

```
 $ ( xinput-gui & ) 
Traceback (most recent call last):
  File "/usr/bin/xinput-gui", line 3, in <module>
    from src import gui, xinput
  File "/usr/lib/python2.7/site-packages/src/gui.py", line 12
    def __init__(self, version: str):
                              ^
SyntaxError: invalid syntax

```

Funnily enough when I removed the file at /usr/bin/xinput-gui and instead ran the file from /usr/local/bin/xinput-gui then I had zero issues.

OS : Fedora 30 Workstation
Kernel Version : 5.1.16-300.fc30.x86_64
Python Version : Python 2.7.16
Python3 Version : Python 3.7.3

As this might confuse beginners whom the app is intended for I thought I'd let you know.
Thanks for the app.

Regards,
Sangeet

**Comment by McSinyx** [comment]
Type hinting requires Python version 3.5 or above. I believe you've install the program using Python 2. I'm editing `setup.py` to explicitly handle this.

**Comment by IvanFon** [comment]
Hey @sangeet, have you had a chance to check if the error is fixed now? As @McSinyx said, the packaging changes should have fixed this issue. Could you follow the updated [installation instructions](https://github.com/IvanFon/xinput-gui#installation) and see if the problem persists?


Thanks! :heart:

**Comment by sangeet** [comment]
Sorry for replying late. Yes, it did work in the first attempt. Closing.

Thanks.
