### ISSUE TITLE
Horizontal split GUI option

### ISSUE THREAD

**Issue by bkuri** [IvanFon/xinput-gui#5]
Please allow for the right side pane to be moved to the bottom in order to maximize screen real estate for those of us with portrait displays. Otherwise it's impossible to read all device/property names:

![2019-07-09-133751_1080x1920_scrot](https://user-images.githubusercontent.com/138886/60914356-fdc1dc00-a24e-11e9-8a8a-e3e968860981.png)

Many thanks in advance!

**Comment by IvanFon** [comment]
Thanks for the suggestion, this is something I plan on adding soon. I may even make it the default, I think a horizontal split could work a lot better for this.

**Comment by bkuri** [comment]
I think it looks great now. :)

![2019-07-13-192326_920x1737_scrot](https://user-images.githubusercontent.com/138886/61177856-e1060b00-a5a4-11e9-8faa-9f70ede6dc12.png)

Could you please increase the maximum width of the "Name" column header? That would allow me to see as much of the device name as possible. Thanks again!

**Comment by IvanFon** [comment]
I’ll try to get to this later today :)

**Comment by IvanFon** [comment]
Column width has been increased in 0.2.2.
